### ISSUE TITLE
Unexpected behavior with the 'factorized' argument

### ISSUE THREAD

**Issue by BenoitPauwels** [quadprog/quadprog#38]
Hi guys,

Many thanks for the Python wrapping of this algorithm I find quite efficient :)

However I'm having difficulties with the use of the 'factorized' argument.

Let's take a simple example.
Say I'm passing the following matrix as first argument:
[ 0 1 ]
[ 1 0 ].
Let's call it `R_inverse`.
I'm also passing `a` = [ 2 3 ] and `factorized=True`.
(For simplicity let's not add any constraint.)

My understanding from [the documentation of parameter `factorized`](https://github.com/quadprog/quadprog/blob/master/quadprog/quadprog.pyx) is that the objective matrix will be understood as
G = R^T R with R = `R_inversed`^{-1}.
In the simple example I'm considering here `R_inversed` is its own inverse and also its own transpose, therefore G should be the identity matrix.
Consequently I'm expecting `quadprog` to return the minimizer G^{-1} `a` = `a` = [ 2 3 ].
However `quadprog` returns [ 2 0 ].

What am I missing?

Thank you for your time,
Benoît

```python
import numpy
import quadprog

R_inverse = numpy.array([[0.0, 1.0], [1.0, 0.0]])
a = numpy.array([2.0, 3.0])
x, _, _, _, _, _ = quadprog.solve_qp(R_inverse, a, factorized=True)
print(x)
# [2. 0.]
assert numpy.allclose(x, a)
# AssertionError
```

**Comment by preeyan** [comment]
Hi @BenoitPauwels , apologies the documentation of this behaviour is not as clear as it could be.

`R` / `R_inverse` should be upper triangular when passing `factorized=True`, so that `R` is the upper triangular Cholesky factor of `G`.

I have clarified the documentation of the `factorized` parameter in https://github.com/quadprog/quadprog/commit/a7f4fa1a59bb962ebd24b8d3ac84fc53c51409f5.

**Comment by BenoitPauwels** [comment]
Hi @preeyan,
Thank you for your clarification :)
Cheers,
Benoît
